

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfd-demo
spec:
  replicas: 2  # Number of replicas
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: pfd-demo
  template:
    metadata:
      labels:
        app: pfd-demo
    spec:
      containers:
      - name: pfd-demo
        image: svhari/pfd-demo:v2  # Updated image tag
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pfd-demo
spec:
  type: LoadBalancer
  selector:
    app: pfd-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
